- docs/AboutUs.md
- docs/team/c5hives.md
> Update AboutUs page for C5hives

- docs/_markbind/layouts/default.md
Resolves: #32 
Update github repo link in navbar, the last sitewide setting not changed yet
> Update sitewide settings

- docs/DeveloperGuide.md
Resolves #42 
Contents of product scope were updated with reference to notes in the shared Google Drive folder.
> Update Target User Profile & Value Proposition for Developer Guide (DG)

- docs/DeveloperGuide.md
Replace existing template use case with "create event" use case for EventTory
> Add create event use case (DG)

- docs/DeveloperGuide.md
Resolves #40 
Also rephrased some sections of the developer guide to be more consistent with word use. Let me know if I missed any terms that should be explicitly defined.
> Update Glossary for Developer Guide (DG)

- src/main/java/seedu/address/logic/Messages.java
- src/main/java/seedu/address/logic/commands/DeleteCommand.java
- src/main/java/seedu/address/logic/commands/DeleteEventCommand.java
- src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
- src/main/java/seedu/address/logic/parser/CliSyntax.java
- src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
- src/main/java/seedu/address/model/Model.java
- src/main/java/seedu/address/model/ModelManager.java
- src/main/java/seedu/address/model/event/EventNameContainsKeywordsPredicate.java
- src/test/java/seedu/address/logic/commands/AddCommandTest.java
- src/test/java/seedu/address/logic/commands/CommandTestUtil.java
- src/test/java/seedu/address/logic/commands/DeleteEventCommandTest.java
- src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
- src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
- src/test/java/seedu/address/model/event/EventNameContainsKeywordsPredicateTest.java
- src/test/java/seedu/address/testutil/EventBuilder.java
- src/test/java/seedu/address/testutil/TypicalEvents.java
- src/test/java/seedu/address/testutil/TypicalIndexes.java
Resolves: #74 
- Added DeleteEventCommand
- Add support in DeleteCommandParser to create the corresponding command (event or vendor)
- Add partial test utils for event to support testing DeleteEventCommand
> Add Support for Deleting Event

- .gitignore
- src/main/resources/view/MainWindow.fxml
- Add .vscode to .gitignore
- Changed title to EventTory
> Administrative chore

- src/main/java/seedu/address/logic/commands/CreateEventCommand.java
- src/test/java/seedu/address/logic/commands/AddCommandTest.java
- src/test/java/seedu/address/logic/commands/CreateEventCommandIntegrationTest.java
- src/test/java/seedu/address/logic/commands/CreateEventCommandTest.java
- src/test/java/seedu/address/logic/commands/CreateVendorCommandIntegrationTest.java
Resolves #78
- Update `CreateEventCommand` to add an `Event` object into the `Model`
- Update tests for `CreateEventCommand`
> Implement Actual Logic for CreateEventCommand

- src/main/java/seedu/address/logic/Logic.java
- src/main/java/seedu/address/logic/LogicManager.java
- src/main/java/seedu/address/ui/EventCard.java
- src/main/java/seedu/address/ui/EventListPanel.java
- src/main/java/seedu/address/ui/MainWindow.java
- src/main/resources/view/EventListCard.fxml
- src/main/resources/view/EventListPanel.fxml
- src/test/java/seedu/address/logic/LogicManagerTest.java
Resolves #64
`list`, `list e/`, `list v/` now works with its corresponding list display.
I used leftPanelPlaceholder for the single pane because i ran into issues using grid pane and i'm not sure how to resolve.
> Set up single pane UI for vendor and event lists

- src/main/java/seedu/address/logic/Logic.java
- src/main/java/seedu/address/logic/LogicManager.java
- src/main/java/seedu/address/logic/commands/ListCommand.java
- src/main/java/seedu/address/model/AddressBook.java
- src/main/java/seedu/address/model/Model.java
- src/main/java/seedu/address/model/ModelManager.java
- src/main/java/seedu/address/model/ReadOnlyAddressBook.java
- src/main/java/seedu/address/ui/EventDetailsPanel.java
- src/main/java/seedu/address/ui/MainWindow.java
- src/main/java/seedu/address/ui/VendorDetailsPanel.java
- src/test/java/seedu/address/logic/LogicManagerTest.java
- src/test/java/seedu/address/logic/commands/CreateEventCommandTest.java
- src/test/java/seedu/address/logic/commands/CreateVendorCommandTest.java
- src/test/java/seedu/address/model/AddressBookTest.java
- src/test/java/seedu/address/model/ModelManagerTest.java
Should show all events also
Should merge #103 first
> Inconsistent list command execute

- src/main/java/seedu/address/logic/Messages.java
- src/main/java/seedu/address/logic/commands/UnassignCommand.java
- src/main/java/seedu/address/logic/parser/AddressBookParser.java
- src/main/java/seedu/address/logic/parser/UnassignCommandParser.java
- src/main/java/seedu/address/model/AddressBook.java
- src/main/java/seedu/address/model/Model.java
- src/main/java/seedu/address/model/ModelManager.java
- src/test/java/seedu/address/logic/commands/AssignCommandTest.java
- src/test/java/seedu/address/logic/commands/CreateEventCommandTest.java
- src/test/java/seedu/address/logic/commands/CreateVendorCommandTest.java
- src/test/java/seedu/address/logic/commands/UnassignCommandTest.java
- src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
- src/test/java/seedu/address/logic/parser/UnassignCommandParserTest.java
Copy the implementation of assign command over to unassign, create dummy functions (TODO) for those needing to access the new associations model.
Tests currently being worked on
Resovles: #85
> Parser implementation for unassign

- build.gradle
- src/main/resources/view/MainWindow.fxml
> Update app name for release

- src/main/java/seedu/address/ui/EventListPanel.java
- src/main/java/seedu/address/ui/MainWindow.java
- src/main/java/seedu/address/ui/VendorDetailsPanel.java
- src/main/java/seedu/address/ui/VendorListPanel.java
- src/main/resources/view/DarkTheme.css
- src/main/resources/view/VendorDetailsPanel.fxml
- Fix long description not wrapping on the details view
- Shift details view to the left and "Assignable X" on the right
Closes #114
> Revamp view behaviour

- src/main/java/seedu/address/ui/EventDetailsPanel.java
- src/main/java/seedu/address/ui/VendorDetailsPanel.java
- src/main/resources/view/DarkTheme.css
- src/main/resources/view/EventDetailsPanel.fxml
- src/main/resources/view/VendorDetailsPanel.fxml
Show the tags associated with vendor and events
> Show tags given to vendor and events

- src/main/java/seedu/address/MainApp.java
> Prep for v1.4 Release

- src/main/java/seedu/address/ui/EventCard.java
- src/main/java/seedu/address/ui/EventDetailsPanel.java
- src/main/java/seedu/address/ui/VendorDetailsPanel.java
- src/main/resources/view/EventListCard.fxml
> Fix bugs related to tags

- src/main/java/seedu/eventtory/logic/commands/ListCommand.java
- src/main/java/seedu/eventtory/logic/commands/ListEventCommand.java
- src/main/java/seedu/eventtory/logic/commands/ListVendorCommand.java
- src/test/java/seedu/eventtory/logic/commands/ListCommandTest.java
- src/test/java/seedu/eventtory/logic/commands/ListEventCommandTest.java
- src/test/java/seedu/eventtory/logic/commands/ListVendorCommandTest.java
> Update equality of list commands

- docs/diagrams/StorageClassDiagram.puml
Resolves #141. Includes the new `Associations` class as well.
> Update UML Diagram for Storage Component

- src/main/java/seedu/eventtory/logic/commands/EditEventCommand.java
> Allow event tags to be properly edited

- src/test/data/JsonSerializableAddressBookTest/invalidEventAddressBook.json
Resolves #163 
Removed extra folder.
Now that's a speedrun B)
> Extra Test Folder after Renaming from Address Book to EventTory

- src/main/java/seedu/eventtory/ui/MainWindow.java
- src/main/resources/view/EventListPanel.fxml
- src/main/resources/view/VendorListPanel.fxml
Resolves #168 
Just a simple grammar fix.
> "Vendors List" and "Events List" should be "Vendor List" and Event List" respectively (no 's')

- src/main/java/seedu/eventtory/logic/commands/EditEventCommand.java
- src/main/java/seedu/eventtory/logic/commands/EditVendorCommand.java
Reading the title explains the PR
Closes #173
> Persist UniqueId when updating Event or Vendor

- src/main/java/seedu/eventtory/model/ModelManager.java
Reading the PR explains the PR
Closes #176
> Fix navigate to default when eventTory is cleared

- src/main/resources/view/CommandBox.fxml
- src/main/resources/view/DarkTheme.css
- src/main/resources/view/EventListPanel.fxml
- src/main/resources/view/Extensions.css
- src/main/resources/view/MainWindow.fxml
- src/main/resources/view/StatusBarFooter.fxml
- src/main/resources/view/VendorListPanel.fxml
Change colour
before
after
before
after
before
after
> Update colour scheme

- src/main/java/seedu/eventtory/logic/Messages.java
- src/main/java/seedu/eventtory/logic/commands/AssignCommand.java
- src/main/java/seedu/eventtory/logic/commands/UnassignCommand.java
- src/main/java/seedu/eventtory/logic/parser/AssignCommandParser.java
- src/test/java/seedu/eventtory/logic/commands/AssignCommandTest.java
- src/test/java/seedu/eventtory/logic/commands/UnassignCommandTest.java
- src/test/java/seedu/eventtory/logic/parser/AssignCommandParserTest.java
- src/test/java/seedu/eventtory/logic/parser/EventToryParserTest.java
Resolves #171 
Added more verbose messages for the user in case of success and failure of command execution.
> Update Assign Command to have Behaviour Consistent with the Updated Unassign Command

- src/test/java/seedu/eventtory/model/commons/tag/TagTest.java
BAD FAILING TESTS IN MAIN BRANCH
> Amend tag tests to reflect forgiving inputs

- src/main/java/seedu/eventtory/logic/Logic.java
- src/main/java/seedu/eventtory/logic/LogicManager.java
- src/main/java/seedu/eventtory/model/Model.java
- src/main/java/seedu/eventtory/model/ModelManager.java
- src/main/java/seedu/eventtory/ui/EventDetailsPanel.java
- src/main/java/seedu/eventtory/ui/VendorDetailsPanel.java
- src/test/java/seedu/eventtory/logic/LogicManagerTest.java
- src/test/java/seedu/eventtory/testutil/ModelStub.java
Closes #183
- Add logic method to get relative index of event or vendor
- Show relative index in detailed view
> Add relative index of viewed object

- docs/UserGuide.md
> Update user guide for unassign command

- docs/UserGuide.md
Resolves #187 
Straightforward change.
> Update User Guide for delete Command

- docs/DeveloperGuide.md
- docs/diagrams/DeleteSequenceDiagram.puml
- docs/diagrams/ParserClasses.puml
AddressBookParser -> EventToryParser
DeleteCommand -> DeleteEventCommand (for this example, delete e/1)
> Update DG for logic component

- src/main/java/seedu/eventtory/model/util/SampleDataUtil.java
> Add sample data

- docs/DeveloperGuide.md
Resolves #201.
- Updated class names in developer guide to reflect new name.
- Class diagram is already indicative of the `Storage` class, so no changes needed for it.
> Update developer guide for storage component

- docs/UserGuide.md
Resolves #216 
Only formatting issues
> Update user guide some more

- docs/DeveloperGuide.md
> Add use case for delete and view

- docs/UserGuide.md
Only visual changes in formatting made.
> Update more formatting for user guide

- docs/DeveloperGuide.md
- docs/diagrams/AssignSequenceDiagram.puml
Resolves #210.
Added implementation details of the `assign` and `unassign` command to the developer guide.
> Add implementation details of the assign and unassign command to DG

- docs/DeveloperGuide.md
> Add find command use case

- docs/DeveloperGuide.md
Resolves #234 
Minor formatting change
> Fix minor formatting issue in manual testing guide

- docs/AboutUs.md
- docs/DeveloperGuide.md
- docs/SettingUp.md
- docs/Testing.md
> Update misc documentation

- docs/UserGuide.md
> Update link to release page

- docs/diagrams/ArchitectureSequenceDiagram.puml
Resolves #242
The diagram looks like this now:
> Fix main sequence diagram

- docs/DeveloperGuide.md
> Remove proposed implementation from DG

- docs/UserGuide.md
> Fix assign command in user guide quick start

- src/main/java/seedu/eventtory/MainApp.java
To be merged after everything done
> Bump version to v1.6
