- README.md
Resolves #30.
Build status badge in README.md is now linked to the `gradle.yml` github action to reflect the build status of our project.
> Update link in build status badge

- docs/DeveloperGuide.md
Resolves #36.
Add use for the `assign` command to the developer guide.
> Add use case for assign command to developer guide

- src/main/java/seedu/address/logic/Messages.java
- src/main/java/seedu/address/logic/commands/AddCommand.java
- src/main/java/seedu/address/logic/commands/CreateVendorCommand.java
- src/main/java/seedu/address/logic/parser/AddressBookParser.java
- src/main/java/seedu/address/logic/parser/CliSyntax.java
- src/main/java/seedu/address/logic/parser/CreateVendorCommandParser.java
- src/test/java/seedu/address/logic/LogicManagerTest.java
- src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
- src/test/java/seedu/address/logic/commands/AddCommandTest.java
- src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
- src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
- src/test/java/seedu/address/testutil/VendorUtil.java
- Change `AddCommand` and `AddCommandParser` to be `CreateVendorCommand` and `CreateVendorCommandParser`
- Change description prefix to be `d/`
- Change `CreateVendorCommand` command to be `create_vendor` 
- Change messages related to `create_vendor`
> Vendor parser support

- src/main/java/seedu/address/logic/commands/CreateEventCommand.java
- src/main/java/seedu/address/logic/parser/AddressBookParser.java
- src/main/java/seedu/address/logic/parser/CliSyntax.java
- src/main/java/seedu/address/logic/parser/CreateEventCommandParser.java
- src/main/java/seedu/address/logic/parser/ParserUtil.java
- src/test/java/seedu/address/logic/commands/CreateEventCommandTest.java
- src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
- src/test/java/seedu/address/logic/parser/CreateEventCommandParserTest.java
- src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Resolves #62 and #76
Test cases are currently hardcoded. Will need to be refactored to use utility classes later on.
- Add `CreateEventCommand` and `CreateEventCommandParser`
- Add a new prefix for date, prefix is `on/`
- Command to add an event is `create_event`
- Add case to handle `create_event`
- Added new test cases and updated existing test cases
> Add parser support for adding new events

- .gitignore
- src/main/java/seedu/address/logic/commands/DeleteCommand.java
- src/main/java/seedu/address/logic/commands/DeleteVendorCommand.java
- src/main/java/seedu/address/logic/parser/CliSyntax.java
- src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
- src/test/java/seedu/address/logic/LogicManagerTest.java
- src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
- src/test/java/seedu/address/logic/commands/DeleteVendorCommandTest.java
- src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
- src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
The command format is updated as per mentioned in #77
`delete v/1`
- Deleting multiple items was not implemented due to the complexity of testing
- The command is extended in such a way adding delete for events should be trivial
> Reworked current delete command for vendor delete

- src/main/java/seedu/address/model/AddressBook.java
- src/main/java/seedu/address/model/Model.java
- src/main/java/seedu/address/model/ModelManager.java
- src/main/java/seedu/address/model/ReadOnlyAddressBook.java
- src/main/java/seedu/address/model/event/Event.java
- src/main/java/seedu/address/model/event/UniqueEventList.java
- src/main/java/seedu/address/model/event/exceptions/DuplicateEventException.java
- src/main/java/seedu/address/model/event/exceptions/EventNotFoundException.java
- src/test/java/seedu/address/logic/commands/AddCommandTest.java
- src/test/java/seedu/address/model/AddressBookTest.java
- src/test/java/seedu/address/model/ModelManagerTest.java
- src/test/java/seedu/address/model/event/EventTest.java
- src/test/java/seedu/address/model/event/UniqueEventListTest.java
Resolves #75 
- Add `isSameEvent` method to `Event` class
- Add `UniqueEventList` to mirror functionality of `UniqueVendorList`
- Add exceptions for handling event operations
- Modified interfaces `Model` and `ReadOnlyAddressBook`
- Update `ModelManager` and `AddressBook` to store events, as well as implement methods that operate on events (from their updated interfaces)
- Update existing `ModelStub` and `AddressBookStub` used in `AddCommandTest` and `AddressBookTest` respectively
- Add basic tests for `UniqueEventList`
No new tests were added to cover the new functionality of `ModelManager` and `AddressBook`. The test coverage will decrease, but I think it'll be more efficient to add said tests after the util classes for event testing have been added. :)
- The current …
> Implement UniqueEventList for parent model

- src/main/java/seedu/address/logic/commands/CreateCommand.java
- src/main/java/seedu/address/logic/commands/CreateEventCommand.java
- src/main/java/seedu/address/logic/commands/CreateVendorCommand.java
- src/main/java/seedu/address/logic/parser/AddressBookParser.java
- src/main/java/seedu/address/logic/parser/CreateCommandParser.java
- src/main/java/seedu/address/logic/parser/CreateEventCommandParser.java
- src/main/java/seedu/address/logic/parser/CreateVendorCommandParser.java
- src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
- src/test/java/seedu/address/logic/LogicManagerTest.java
- src/test/java/seedu/address/logic/commands/CreateVendorCommandTest.java
- src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
- src/test/java/seedu/address/logic/parser/CreateCommandParserTest.java
- src/test/java/seedu/address/logic/parser/CreateEventCommandParserTest.java
- src/test/java/seedu/address/logic/parser/CreateVendorCommandParserTest.java
- src/test/java/seedu/address/testutil/EventUtil.java
- src/test/java/seedu/address/testutil/VendorUtil.java
Resolves #84 
The class hierarchy for commands to create vendors and events is similar to that of `DeleteCommand`. However, it should be noted that the parse logic to create a vendor/event is separated into two parsers.
- `CreateCommandParser` is in charge of understanding the command and passing the arguments to either `CreateVendorCommandParser` or `CreateEventCommandParser`
- Unlike `DeleteVendorCommand` and `DeleteEventCommand`, the create commands do not share any parameters. Hence, the implementation of the `CreateCommand` class is barebones.
> Refactor CreateEventCommand and CreateVendorCommand to stem from the same Parent Class

- src/main/java/seedu/address/storage/JsonAdaptedEvent.java
- src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
- src/test/data/JsonSerializableAddressBookTest/duplicateEventAddressBook.json
- src/test/data/JsonSerializableAddressBookTest/duplicateVendorAddressBook.json
- src/test/data/JsonSerializableAddressBookTest/invalidEventAddressBook.json
- src/test/data/JsonSerializableAddressBookTest/invalidVendorAddressBook.json
- src/test/data/JsonSerializableAddressBookTest/typicalEventsAddressBook.json
- src/test/data/JsonSerializableAddressBookTest/typicalVendorsAddressBook.json
- src/test/java/seedu/address/storage/JsonAdaptedEventTest.java
- src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
Resolves #80 
- Add `JsonAdaptedEvent`
- Update `JsonSerializableAddressBook` to store a list of `JsonAdaptedEvent` objects.
- Add tests for both classes, which includes new test `.json` files.
- Events in the address book can technically be saved into json. However, as new events cannot be added to the event list yet, this would mean the .json file would not contain events.
- Tests for `JsonAddressBookStorage` has not been updated because `CreateEventCommand` is still not functional (thanks to me).
- Tests will need to be updated to ensure that the loading the saving of both vendors and events is working as intended.
> Allow events in memory to be persistent

- src/main/java/seedu/address/model/AddressBook.java
- src/main/java/seedu/address/model/Model.java
- src/main/java/seedu/address/model/ModelManager.java
- src/test/java/seedu/address/logic/commands/CreateEventCommandTest.java
- src/test/java/seedu/address/logic/commands/CreateVendorCommandTest.java
- src/test/java/seedu/address/model/AddressBookTest.java
- src/test/java/seedu/address/model/ModelManagerTest.java
Add methods to `AddressBook`, `ModelManager` and `Model` to get the list of associated vendors and events. Resolves #98.
> Add get associated vendors and events

- src/main/java/seedu/address/logic/commands/DeleteEventCommand.java
- src/main/java/seedu/address/logic/commands/DeleteVendorCommand.java
- src/main/java/seedu/address/model/AddressBook.java
- src/main/java/seedu/address/model/Model.java
- src/main/java/seedu/address/model/ModelManager.java
- src/main/java/seedu/address/model/commons/exceptions/AssociationDeleteException.java
- src/test/java/seedu/address/logic/commands/DeleteEventCommandTest.java
- src/test/java/seedu/address/logic/commands/DeleteVendorCommandTest.java
- src/test/java/seedu/address/model/AddressBookTest.java
- src/test/java/seedu/address/testutil/TypicalVendorsEventsCombined.java
- Created a new exception under `model/commons/exceptions` for handling associated delete fails
- could be made to inherit from a parent delete exception class but don't see a need to
- Update delete commands to display error msg when trying to delete an associated event/model
- does not show which event it is associated to, just whether it is associated to any
> Update delete command to display failure message for associated event/vendor

- src/main/java/seedu/address/logic/commands/CreateCommand.java
- src/main/java/seedu/address/logic/commands/CreateEventCommand.java
- src/main/java/seedu/address/logic/commands/CreateVendorCommand.java
- src/main/java/seedu/address/logic/commands/DeleteCommand.java
- src/main/java/seedu/address/logic/commands/ViewCommand.java
- Standardize separate examples for both vendor and event
- Parameters can still use `<v/ OR e/>`
- Add examples for `createCommand` and `createEventCommand`
Resolves: #124
> Standardize and update message usage descriptors

- src/main/java/seedu/eventtory/ui/EventDetailsPanel.java
- src/main/java/seedu/eventtory/ui/EventListPanel.java
- src/main/java/seedu/eventtory/ui/MainWindow.java
- src/main/java/seedu/eventtory/ui/VendorDetailsPanel.java
- src/main/java/seedu/eventtory/ui/VendorListPanel.java
- src/main/resources/view/CommandBox.fxml
- src/main/resources/view/EventListPanel.fxml
- src/main/resources/view/Extensions.css
- src/main/resources/view/ResultDisplay.fxml
- src/main/resources/view/VendorListPanel.fxml
It is possible to tab to focus on the different elements and use the arrow keys to scroll, but it was not possible to find out what was focused.
- Add highlights to show focused elements
> Add highlight to focused elements

- src/main/java/seedu/eventtory/model/ModelManager.java
- src/main/java/seedu/eventtory/model/event/Event.java
- src/main/java/seedu/eventtory/model/vendor/Vendor.java
- src/main/java/seedu/eventtory/ui/UiState.java
- src/test/java/seedu/eventtory/logic/commands/DeleteEventCommandTest.java
- src/test/java/seedu/eventtory/logic/commands/DeleteVendorCommandTest.java
- src/test/java/seedu/eventtory/model/event/EventTest.java
- src/test/java/seedu/eventtory/model/vendor/VendorTest.java
Reading the PR explains the PR
Closes #165 
Additional Changes
- Method to check for `UniqueId` equality
View is only changed to default when:
- Deleted object is current selected object
- Deletion is successful (explicit by error not being thrown)
- Current view is detailed view of the deleted object
> Return to default view when selected object is deleted

- src/main/java/seedu/eventtory/model/commons/tag/Tag.java
- src/main/java/seedu/eventtory/storage/JsonAdaptedTag.java
- src/test/java/seedu/eventtory/model/commons/tag/TagTest.java
Resolves #164 
Tags are now stored in lowercase. 
- Tags such as "Name", "NAME" and "name" will all be treated to be "name".
- This might be bad for tags that use captialisation to differentiate between acronyms and other words. E.g. "CAT" (Caterpillar Inc.) and "cat" (the animal), but this can be addressed in #167 by allowed non-alphanumeric characters
> Tags are Case Sensitive

- src/main/java/seedu/eventtory/model/commons/name/Name.java
- src/main/java/seedu/eventtory/model/commons/tag/Tag.java
- src/test/java/seedu/eventtory/logic/commands/CommandTestUtil.java
- src/test/java/seedu/eventtory/logic/parser/CreateEventCommandParserTest.java
- src/test/java/seedu/eventtory/logic/parser/ParserUtilTest.java
- src/test/java/seedu/eventtory/model/commons/name/NameTest.java
- src/test/java/seedu/eventtory/storage/JsonAdaptedEventTest.java
- src/test/java/seedu/eventtory/storage/JsonAdaptedVendorTest.java
Resolves #167
Changed input fields to accept more input strings.
1. Must start with an alphanumeric character <- not sure if this is too arbitrary
2. Must NOT contain '/'
1. Can contain only alphanumeric characters, hyphens '-', and underscores '_' (this naturally excludes the use of '/' as well)
2. Cannot be made up of only hyphens '-' and underscores '_'
3. Can start with hyphens '-' and underscores '_' (if the user chooses to do so)
4. Is more relaxed compared to `Name`
1. No change, should it be changed to disallow forward slashes '/' as well?
> Make inputs more forgiving

- src/main/java/seedu/eventtory/model/commons/tag/Tag.java
- src/test/java/seedu/eventtory/model/commons/tag/TagTest.java
Resolves #205
Tags can only be of length 30 max now. This is to prevent ugly rendering.
> Tag cannot display long inputs

- src/main/java/seedu/eventtory/logic/Logic.java
- src/main/java/seedu/eventtory/logic/LogicManager.java
- src/main/java/seedu/eventtory/logic/commands/ViewEventCommand.java
- src/main/java/seedu/eventtory/logic/commands/ViewVendorCommand.java
- src/main/java/seedu/eventtory/model/Model.java
- src/main/java/seedu/eventtory/model/ModelManager.java
- src/main/java/seedu/eventtory/ui/EventDetailsPanel.java
- src/main/java/seedu/eventtory/ui/VendorDetailsPanel.java
- src/main/resources/view/EventDetailsPanel.fxml
- src/main/resources/view/VendorDetailsPanel.fxml
- src/test/java/seedu/eventtory/logic/LogicManagerTest.java
- src/test/java/seedu/eventtory/testutil/ModelStub.java
Index of viewed object was dependent on filteredList to be updated which depended on viewedObject to be updated first. It is possible to update indexOfViewedObject together with viewedObject without waiting for filteredList to be updated. So it is refactored out
> Fix bugs regarding viewed object index

- docs/DeveloperGuide.md
Resolves #236.
Add use case to create vendor, and update create event use case.
> 236 update create comand in dg

- src/main/java/seedu/eventtory/logic/commands/ViewEventCommand.java
- src/main/java/seedu/eventtory/logic/commands/ViewVendorCommand.java
- src/main/java/seedu/eventtory/model/ModelManager.java
- Viewing an item that was filtered out will result in the relative index label to be 0 **(unexpected behaviour)**
- Reset the filtered list of the item before viewing to prevent it not being able to be found
- Reset is only done when going from one item view to another to maintain the find operation as long as possible
> Fix index 0 showing up after nested find and view operation

- docs/UserGuide.md
Resolves #319 
1. Added an example for each date format.
2. Add disclaimer about how dates are displayed after getting parsed (input format != output format).
3. Add disclaimer about how input dates in the past will still be acceptable.
4. Add disclaimer about how there are only a certain number of months and days in the year (this one is pretty dumb).
Also reformatted description for `Tag` as a bonus!
> Better documentation for date formats

- docs/DeveloperGuide.md
Resolves #337 
- Added an extra section under "Planned Enhancements" to make command words case insensitive.
> Add Enchancement in Documentation for Making Commands Case-Insensitive
